Oefenweb/ansible-postfix

- README.md
- defaults/main.yml
- templates/etc/postfix/main.cf.j2
* Add variable `postfix_relaytls` to enable use of TLS per [SES Postfix documentation]
* Add AWS SES usage example in README
[SES Postfix documentation]: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/postfix.html
> Add AWS SES compatibility

- defaults/main.yml
- templates/etc/postfix/main.cf.j2
The default value for inet_protocols has been 'all' since Postfix 2.9 (http://www.postfix.org/postconf.5.html#inet_protocols), which will enable IPv6.
Seems to me that the default should be to use IPv6 where available.
> Reset inet_protocols to the Postfix >=2.9 default of 'all' to enable IPv6

- README.md
- defaults/main.yml
- handlers/main.yml
- tasks/main.yml
- templates/etc/postfix/main.cf.j2
Hi @tersmitten,
this PR allows the user to optionally configure the sender_canonical_maps feature of Postix which allow rewriting of the sender.
We have a use case here where the relayhost of the provider only accepts certain sender names.
Let me know if you'd like to have any changes on this.
Best 
Jard
> add optional sender_canonical_maps

- README.md
- defaults/main.yml
- templates/etc/postfix/main.cf.j2
Allowing custom smtpd_banner can be useful to prevent announcing software or version to malicious people or scripts.
Reference: https://cisofy.com/controls/MAIL-8818/
> Make smtpd_banner configurable

- README.md
- defaults/main.yml
- templates/etc/postfix/main.cf.j2
Disable the SMTP VRFY command. This stops some techniques used to harvest email addresses.
https://linux-audit.com/postfix-hardening-guide-for-security-and-privacy/
> Disable the SMTP VRFY command

- README.md
- defaults/main.yml
- handlers/main.yml
- tasks/main.yml
- templates/etc/postfix/main.cf.j2
Adds option to use virtual aliases for non-local email forwarding. Added example to documentation.
I also added $mydomain to mydestination in the config file, since $mydomain is often different from $myhostname.
> Virtual aliases

- handlers/main.yml
> Handlers are run in the order they are listed, not in the order that they are notified.
see: https://docs.ansible.com/ansible/latest/reference_appendices/glossary.html#notify
> Fixed order of handlers

- README.md
Linked issue: #47
The repo has been moved from https://galaxy.ansible.com/tersmitten/postfix to https://galaxy.ansible.com/oefenweb/postfix. As a consequence the ansible galaxy badge in the Readme no longer points to the proper url.
Ansible galaxy badge in the Readme points to the proper url.
> Fix ansible galaxy badge link in README

- README.md
- defaults/main.yml
- handlers/main.yml
- tasks/main.yml
- templates/etc/postfix/main.cf.j2
I need to manage recipient_canonical_maps but PR #59 introducing this feature is stalled because of another feature in the same PR.
So just cherry-picking the commit for recipient_canonical_maps to have it merge quickly.
Thanks to @toebivankenoebi for the work on this feature.
> added possibility for recipient_canoncial_maps, identical to sender_canonical_maps

- tasks/main.yml
Postfix expects aliases.db to exist, while your role has a handler to generate it if you modify the aliases file it does not verify the file exists on a fresh install where you don't change the aliases file. The debian installer does not automatically generate the file unless you use the debconf which ansible does not, and despite you setting it up it does not run. Plus since it is necessary for postfix to run without complaint it is a good idea to check for it anyway.
> Ensure aliases.db is always generated

- README.md
- defaults/main.yml
- templates/etc/postfix/main.cf.j2
- templates/etc/postfix/sasl_passwd.j2
To use the MX records of a domain as relay host, there must be no square brackets around the relayhost.
The advantage is that multiple hosts can be specified in the DNS with type MX.
> Add posibility to use DNS MX records for relayhost

- handlers/main.yml
The best practice for running multiple handlers on one notify is using listeners.
> Use handler listeners

- README.md
- defaults/main.yml
- templates/etc/postfix/main.cf.j2
Hey,
for one of my servers it was needed to set the param smtp_sasl_tls_security_options, i,ve just added the param in the defaults and template.
> added smtp_sasl_tls_security_options config parameter

- tasks/main.yml
- templates/etc/aliases.j2
Using the `lineinfile` module causes the deletion of aliases in the vars
files not to be reflected in the actual `/etc/aliases` file, so we may
end up with dangling entries.
Using a template to manage the whole file makes sense since this file
should be "owned" by the postfix installation/configuration, so we want
it to be rebuilt as a whole from the vars configuration instead of just
editing some lines.
Closes #78
Signed-off-by: L. Alberto Giménez <agimenez@sysvalve.es>
> Manage /etc/aliases with the template module

- README.md
- templates/etc/postfix/main.cf.j2
Zabbix is sad when it does not see the `220 localhost ESMTP Postfix (Ubuntu)` welcome message. 😿
> feat: add support for smtpd_client_restrictions

- tasks/main.yml
Setting the _relay_host_ variable doesn't necessary imply that SASL authentication is used. My use case is a German university where the relay is protected by the network.
BTW: I would always write this file to ensure idempotency when variables are changed.
> Skip writing of SASL password file when SASL authentication is disabled

- README.md
- templates/etc/postfix/main.cf.j2
Add variables for following configuration items:
- smtpd_helo_restrictions
- smtpd_sender_restrictions
- smtpd_recipient_restrictions
- smtpd_data_restrictions
> Add support for more smtpd restrictions

- tasks/main.yml
Currently the regex can match a substring of line we are looking for.
This patch changes the regexes to include one whitespace.
> Make lineinfile regex more specific

- defaults/main.yml
🔺 `postfix_header_checks_database_type = regexp` default variable is missing and causes role to fail.
> `postfix_header_checks_database_type` variable missing from `defaults/main.yml`

- README.md
- defaults/main.yml
The VRFY command  can be used to see if an email address is valid on the mail server. To make existing email addresses public defies security and privacy principles, so the VRFY command should be disabled. In addition, I don't see a practical use case for the administrator of the Postfix server.
> Set default for postfix_disable_vrfy_command to true.

- handlers/main.yml
`sasl_password.db` is not encrypted, and can be read e.g. using the
command `string sasl_password.db`.  Change its permission mode to 0600, so
it can only be read by the file's owner, `root`.
Implemented by creating the file using `postmap`, without the `-p` flag, so
it will inherit the desired permissions from the input file
`sasl_password`.  Previously `-p` was used, to set the default mode 0644
(readable by all users).
This was tested on Debian 10, and accords with the postfix docs.
> http://www.postfix.org/SOHO_README.html
>
> Important
>
> Keep the SASL client password file in /etc/postfix, and make the file
> read+write only for root to protect the username/password combinations
> against other users. The Postfix SMTP client will still be able to read
> the SASL client passwords. It …
> Do not allow non-root users on mail server to read postfix_sasl_password

- README.md
- defaults/main.yml
- templates/etc/postfix/main.cf.j2
Request that the Postfix SMTP client connects using the legacy SMTPS protocol instead of using the STARTTLS command.
Postfix needs the following setting in `main.cf` if the `relayhost` uses port `465`.
```
smtp_tls_wrappermode = yes
```
http://www.postfix.org/postconf.5.html#smtp_tls_wrappermode
> feature: smtp_tls_wrappermode for relayhost_port 465

- README.md
- templates/etc/postfix/main.cf.j2
This PR adds support for **smtpd_security_level** option ([here](http://www.postfix.org/postconf.5.html#smtpd_tls_security_level)). If the variable is undefined then no changes (including linefeeds) are introduced to main.cf.
> Support smtpd_tls_security_level option

- README.md
- defaults/main.yml
- handlers/main.yml
- tasks/main.yml
- templates/etc/aliases.j2
- templates/etc/postfix/main.cf.j2
This PR allows configuring `alias_database` as `regexp`. This topic was already discussed in issue #88, but could not work because the alias db syntax was incorrect for regexp type (containing a colon between user and alias).
A new option `postfix_alias_database_type` was introduced which is used for `alias_database` and `alias_maps` when specified (`postfix_default_database_type` is used otherwise), and a correct regexp database file is created from the `postfix_aliases` list.
> Option to set alias database type to regexp

- README.md
- defaults/main.yml
- templates/etc/postfix/main.cf.j2
Because I need to specify  which interface my postfix should use when sending e-mails
> Add support for smtp_bind_address* parameters

- templates/etc/postfix/header_checks.j2
- templates/etc/postfix/main.cf.j2
- templates/etc/postfix/sasl_passwd.j2
This allows having multi-line `ansible_managed` strings. See https://github.com/Oefenweb/ansible-postfix/issues/146
> ansible managed syntax, refs #146

- tasks/main.yml
newer Ansible enforces this. 
See: https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_12.html#example-implicit-boolean-conversion
> make sure this evaluates to boolean
